#!/bin/bash

CONFIG_FILE="../data/config.ini"

# Default Values
DEFAULT_DEST="$HOME/Downloads"
DEFAULT_BROWSER="chrome"
OPEN_WHEN_DONE="N"
INTRO_ANIMATION="full"
SPEED_PROFILE="turbo"
CONCURRENT_FRAGMENTS="16"
DOWNLOAD_RETRIES="20"
ARIA_CONNECTIONS="16"
ARIA_SPLITS="16"
ARIA_CHUNK="1M"
EMBED_METADATA="S"
EMBED_THUMBNAIL="S"
DOWNLOAD_SUBS="N"
DOWNLOAD_ARCHIVE="N"

load_config() {
    if [ -f "$CONFIG_FILE" ]; then
        while IFS='=' read -r key value; do
            case "$key" in
                DEFAULT_DEST) DEFAULT_DEST="$value" ;;
                DEFAULT_BROWSER) DEFAULT_BROWSER="$value" ;;
                OPEN_WHEN_DONE) OPEN_WHEN_DONE="$value" ;;
                INTRO_ANIMATION) INTRO_ANIMATION="$value" ;;
                SPEED_PROFILE) SPEED_PROFILE="$value" ;;
                CONCURRENT_FRAGMENTS) CONCURRENT_FRAGMENTS="$value" ;;
                DOWNLOAD_RETRIES) DOWNLOAD_RETRIES="$value" ;;
                ARIA_CONNECTIONS) ARIA_CONNECTIONS="$value" ;;
                ARIA_SPLITS) ARIA_SPLITS="$value" ;;
                ARIA_CHUNK) ARIA_CHUNK="$value" ;;
                EMBED_METADATA) EMBED_METADATA="$value" ;;
                EMBED_THUMBNAIL) EMBED_THUMBNAIL="$value" ;;
                DOWNLOAD_SUBS) DOWNLOAD_SUBS="$value" ;;
                DOWNLOAD_ARCHIVE) DOWNLOAD_ARCHIVE="$value" ;;
            esac
        done < "$CONFIG_FILE"
    fi
}

save_config() {
    mkdir -p "$(dirname "$CONFIG_FILE")"
    cat <<EOF > "$CONFIG_FILE"
DEFAULT_DEST=$DEFAULT_DEST
DEFAULT_BROWSER=$DEFAULT_BROWSER
OPEN_WHEN_DONE=$OPEN_WHEN_DONE
INTRO_ANIMATION=$INTRO_ANIMATION
SPEED_PROFILE=$SPEED_PROFILE
CONCURRENT_FRAGMENTS=$CONCURRENT_FRAGMENTS
DOWNLOAD_RETRIES=$DOWNLOAD_RETRIES
ARIA_CONNECTIONS=$ARIA_CONNECTIONS
ARIA_SPLITS=$ARIA_SPLITS
ARIA_CHUNK=$ARIA_CHUNK
EMBED_METADATA=$EMBED_METADATA
EMBED_THUMBNAIL=$EMBED_THUMBNAIL
DOWNLOAD_SUBS=$DOWNLOAD_SUBS
DOWNLOAD_ARCHIVE=$DOWNLOAD_ARCHIVE
EOF
}
